### ISSUE TITLE
allow building of model from yaml

### ISSUE THREAD

**Issue by roninsightrx** [InsightRX/luna#9]
e.g. 
```
runs:
  - id: run1
    build:
      absorption: FO
      elimination: FO
      peripheral: 1
      transits: 0
      lagtime: OFF
```
https://pharmpy.github.io/latest/mfl.html
